apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-model
  labels:
    app: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
      - name: my-model-container
        image: model-image:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Never
