apiVersion: v1
kind: Service
metadata:
  name: my-model-service
  labels:
    app: mlops
spec:
  type: NodePort
  selector:
    app: mlops
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000

